apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qingyu.fullname" . }}
  labels:
    {{- include "qingyu.labels" . | nindent 4 }}
type: Opaque
stringData:
  BLOG_ADMIN_SETUP_KEY: {{ .Values.secrets.adminSetupKey | quote }}
  BLOG_WRITE_TOKEN: {{ .Values.secrets.writeToken | quote }}
  BLOG_PREVIEW_SECRET: {{ .Values.secrets.previewSecret | quote }}